image: ubuntu
stack: python 3.6

environment:
  PYTHON: 3.6
  DJANGO_SETTINGS_MODULE: rooibos_settings.test
  PYTHONPATH: .

install:
  - source ~/venv${PYTHON}/bin/activate
  - pip install -U -q wheel twine
  - pip install -r requirements.txt

build_script:
  - source ~/venv${PYTHON}/bin/activate
  - django-admin test
  - VERSION=$(git describe --always)
  - NAME=rooibos-$APPVEYOR_REPO_BRANCH-$VERSION-build$APPVEYOR_BUILD_NUMBER
  - mkdir -p appveyor-build
  - echo VERSION=\"$VERSION\" > rooibos/version.py
  - git add rooibos/version.py
  - git commit -m "Update version number"
  - git archive --prefix rooibos-$VERSION/ -o appveyor-build/$NAME.tar.gz HEAD
  - mkdir -p appveyor-build-temp
  - cd appveyor-build-temp
  - tar xzf ../appveyor-build/$NAME.tar.gz
  - zip -r ../appveyor-build/$NAME.zip *
  - cd ..

test: off

artifacts:
  - path: appveyor-build/*

deploy:
  provider: S3
  access_key_id: AKIAJTFTACX5PEZXKG3Q
  secret_access_key:
    secure: rQGYSegd6l2CN6gcS/vOptJ7Q7v6rLjdlDCLm1MKns3StSTrAHjoIbXRIMuZymoM
  bucket: vrchost-jenkins
  set_public: true
  folder: builds/$APPVEYOR_REPO_BRANCH
