image: ubuntu
stack: python 3.6

environment:
  PYTHON: 3.6
  DJANGO_SETTINGS_MODULE: rooibos.settings.test
  PYTHONPATH: .
  TWINE_REPOSITORY: testpypi
  TWINE_USERNAME: __token__
  TWINE_PASSWORD:
    secure: OROGS4klyQKNAlNz7wtLTG28KjvQpKkHVWBWfAG9oOdPlmxrP+ARpEDMH9TD+7igCxG0LAB3PZVCdBkIazZe9KtIgGTwkyobc4Rl7Dtm3e0DVw7brfc18ORf4iYs6ppiZsZsdBU+2z+gc4ob3agBbpdLQDq4LZZsOviE34xxMQ6iLU+F0Zpk0hap5v5CqnwYZxMFJwSDhjOmO13gWJZlwJYinvKazQMlZAYasojLVU0skRG+9MTYLvWpWZKRsm+Z

install:
  - sudo apt-get install -y libsasl2-dev libldap2-dev
  - source ~/venv${PYTHON}/bin/activate
  - pip install -U -q wheel twine

build_script:
  - python setup.py bdist_wheel

test_script:
  - source ~/venv${PYTHON}/bin/activate
  - pip install dist/mdid*.whl
  - django-admin test

after_test:
  - twine upload dist/mdid*.whl
