name: Build

on:
  push:

env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build:
    if: github.repository == 'vrchost/rooibos'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install requirements
        run: |
          python -m pip install -U -q pip wheel

      - name: Build
        run: |
          rm -f -- dist/*
          python setup.py bdist_wheel

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: dist/*
